### ISSUE TITLE
Visual Studio 2015 支持

### ISSUE THREAD

**Issue by happlebao** [guaxiao/renderer.gua#4]
1. 在这个 [pull request](https://github.com/guaxiao/renderer.gua/pull/1) 中，你建议把`project file`单独放到一个文件夹中。对应的`lib`的`dll`也要放过去吗？
因为要支持`VS2015`的话，就要重新编译源代码。所以就会有不同的 lib 和 dll。
经测试，官方最新的 [`build`](https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/sdl-visualstudio-2519.zip) 是可以在`VS2015`下面用的。
![VS2015 result](http://i.imgur.com/WLdouXz.png)

2. 能说下为什么用`sdl1`而不是`sdl2`吗？因为最新的`build`用的是`sdl2`。
我照着官方的[迁移指南](https://wiki.libsdl.org/MigrationGuide)对`windows.h`做了些修改，你看看？https://github.com/happlebao/renderer.gua/blob/sdl2/src/window.h 
你觉得那个`null` 的检查需不需要单独抽成一个函数？

觉得行的话我就开个 pull request。
@guaxiao @icylogic

**Comment by icylogic** [comment]
我觉得, 同时两个 lib 有点不好...
我用的还是 1.2.15, 因为原 repo 也是, 我也不清楚为什么没有用2, 可能 @guaxiao 更熟悉 2 吧... 如果要改的话最好决定好再搞这些工程文件, 不能 vs2013/2015 用 2, 其他平台/mingw 用 1.2.15 吧. 应该只保留一个 lib

vs2015 需要重新编译 sdl, 这个我也测试过了, 我只是觉得这样有点 dirty, 自己编译的lib在其他x86/x64的vs200x/2010下未必可以用, 但是官方提供下载的 lib (也就是我加进去的) 是做过测试的. 所以我选择把项目设置改成使用v120工具链, 这样可以直接使用官方提供的预编译包. 更低版本的(2010)也只需要改一下工具链. 这个应该在导入的时候 vs 会自动完成.

**Comment by guaxiao** [comment]
sdl.dll 放根目录是给 MinGW 的用户用的

用1还是用2没什么差别，只是我没想到1不能在 vs2015 上 build。

我看了一下你的代码，除了一些格式、缩进的问题外，以下这处也是不可取的，不应该使用 640 这种magic number
SDL_UpdateTexture(_texture, NULL, (uint32_t *)_screen->pixels, 640 * sizeof(uint32_t));

**Comment by guaxiao** [comment]
只要vs2010 2015都能打开不作任何设置就能编译运行，那用2还是1.2都无所谓。
我没有vs，所以还请你们商量一下如何解决这个问题。

用sdl只是为了借个壳可以跨平台画点，因为如果用glfw + opengl的话需要装的东西就多了，而我希望装的东西越少越好（因为都是多余的），以后不会用到它的其他特性。

**Comment by happlebao** [comment]
@icylogic 
同时两个`lib`当然不好... 留在那是因为我不能改 `os x`，`linux` 的设置。
`vs2010`不用管了吧，`vs2013 / vs2015` 都免费了，我这也没装 `vs2010`。你那有装？
过几天`vs2015`正式版就出了，很多人肯定就只装`vs2015`了。如果只装`vs2015`的话，不会有`v120`工具链可选吧？

**Comment by happlebao** [comment]
@guaxiao 
那`dll`和`lib`还有`include`目录应该像`osx`一样放在`platform/win`下对吗？ 
缩进是因为我忘记`vs`默认是用`tab`了，已修正。格式不知指的是什么？

**Comment by happlebao** [comment]
@guaxiao 
magic number 已移除：https://github.com/happlebao/renderer.gua/commit/038c4db11fa17266c5c87dec1d1cfe05b7fb565d
我之前没用过`sdl`，请见谅。

**Comment by icylogic** [comment]
@happlebao 那就使用 SDL2 吧, 仿照 osx 把 lib 和 include 放在 win 下. 

另外关于 mingw 使用 SDL2, makefile 中 OSX 没有用到根目录下的 SDL-1.2.15, 只有 mingw 用到了, OSX 用得是 platform/osx 下的库. 所以能否把 mingw 的[SDL2依赖](https://www.libsdl.org/release/SDL2-devel-2.0.3-mingw.tar.gz)也同样放到 platform 下, makefile 里改一下[这一行](https://github.com/guaxiao/renderer.gua/blob/master/Makefile#23)应该就可以了

- platform
  - win
    - SDL2-VisualStudio
    - SDL2-mingw
    - main.cpp
  - osx
    - SDL.framework
    - ...

**Comment by happlebao** [comment]
@icylogic 目录名要包括`build number`和小版本号吗？
像这样: `SDL2-visualstudio-2519` 和 `SDL2-2.0.3`。

**Comment by happlebao** [comment]
@guaxiao `include`中的头文件要统一放到根目录吗？`vs`，`osx`，`linux`，`mingw`各一份不太好吧？

**Comment by icylogic** [comment]
@happlebao 看到你已经包括版本号, 就这样也没问题, 不用纠结这个啦. 

我觉得你测试好, 把代码根据建议修正好, 可以提一个PR了吧. 

我觉得 include 这个目前这样可以先不用管, 如果要改也是 @guaxiao 统一改吧. 毕竟涉及所有平台.

**Comment by happlebao** [comment]
`sdl2.0.3`在`mingw32`下有[bug](https://forums.libsdl.org/viewtopic.php?t=10284&sid=2888ecbb7fc048bbb49de54e0c357dda)。
[这里](https://buildbot.libsdl.org/sdl-builds/)也没有mingw对应的版本。
要修的话要自己编译或者改头文件，这更dirty了。

`SDL-1.2.15/lib`你忘记上传了，但没有任何人报错，说明没人用`mingw`...
既然有`vs`了，要不`mingw`就不管了？

**Comment by happlebao** [comment]
@icylogic 缩进我改了，magic number我也移除了。就等@guaxiao 来讲下我格式哪有问题了。

**Comment by guaxiao** [comment]
@icylogic ，我希望你能做成这样，用 sdl1.2，改一个 vs2015 能用的静态库，无论是否 dirty，只要能让人打开 vs 就能编译就成。
如果vs2013不能用这个静态库，就给2013再来一个它能用的静态库就好。

**Comment by happlebao** [comment]
@guaxiao 是因为 mingw 用不了所以决定还是用1.2吗？

**Comment by guaxiao** [comment]
这倒不是主要的。

主要原因在于这个项目跟sdl没什么关系，只是借用它的壳，只要附带静态库能编译运行，那么它多dirty都完全无所谓。

我选用它的原因是希望尽可能地排除安装开发环境等无益开销的干扰，只要你给出能运行的工程文件，用修改过的静态库一点问题都没有（反正用户不需要关心这些鬼东西）。

**Comment by happlebao** [comment]
看起来 @icylogic 好像没空，那我来吧。

**Comment by happlebao** [comment]
@guaxiao 完工。
静态库需要用`vs2013`和`vs2015`分开编译。
现在只加了`x86`的。`x64`要一起加吗？
`mingw`也在这个`branch`里面一起迁移到`platform\win`还是怎样？

@icylogic 你测试下？

**Comment by plinx** [comment]
@happlebao 
经测试，若系统中未安装 vs2015，使用 vs2013 编译 projects/vs2013 将报错：丢失 vcruntime140.dll。

**Comment by guaxiao** [comment]
我就说这 vs 其实有点妖孽。。mingw是不会出这种问题的

**Comment by plinx** [comment]
嗯，可能是共存多版本 VS 系统中，自动选择使用高版本的 vcruntime.dll，也可能是工程保存了最后一次编译的 VS 版本信息。

**Comment by happlebao** [comment]
@plinx windows 10 还是 windows 8.1 ?我装个虚拟机看一下。

**Comment by plinx** [comment]
![image](https://cloud.githubusercontent.com/assets/3380744/9028712/5f666fd2-39b4-11e5-8448-d5285a6a0bc2.png)

![image](https://cloud.githubusercontent.com/assets/3380744/9028720/7fb2bc46-39b4-11e5-9336-0fd9e4931321.png)

@happlebao ，系统为 windows 8.1，系统 VS 最高版本为 VS2013。

**Comment by guaxiao** [comment]
@happlebao 我修复了 VS 下黑屏的 bug，等我稍后 push 到 dev（因为还有其他改动）。
主要是浮点数 memset 的问题，感谢微软。
修复办法是 canvas.cpp 里用
std::fill(_depthBuffer, _depthBuffer + _bufferSize, FLT_MAX);
来替换之前的memset

丢失 vcruntime140.dll 的问题，请看以下链接
http://blogs.msdn.com/b/vcblog/archive/2014/06/10/the-great-crt-refactoring.aspx
所以也有可能是 @plinx 的安装有问题。。需要找一个只装了 2013 的电脑测试一下。
在此一并感谢微软

**Comment by happlebao** [comment]
虚拟机安装中。
我猜可能是sdl没编译好。

**Comment by plinx** [comment]
> Starting with Visual Studio "14," we will stop releasing new versions of the CRT with each release of Visual Studio. Whereas before we would have released msvcr140.dll in this forthcoming release, then msvcr150.dll in the next release, we will instead release one new CRT in Visual Studio "14" then update that version in-place in subsequent releases, maintaining backwards compatibility for existing programs.

从链接的描述来看，这里的 "14" 应该意指 VS2015。
确实也可能是我安装有问题，今天回去我会进一步测试（真机 + 虚拟机）。

**Comment by guaxiao** [comment]
pull 我最新的 dev，应该能解决 vs 黑屏的问题。
sdl 官网的 lib 应该可以用于 2013 吧？我随便猜的。
要是麻烦的话就不要弄了，我可以把 window 拆开，用 sdl1 或者 sdl2 都可以。

**Comment by happlebao** [comment]
@guaxiao 黑屏问题已经解决.
@plinx 你那个问题其实是因为在`post build event`拷贝`dll`的时候拷错了,已解决.
分别在`windows 10+vs2015`和`windows 8.1+vs2013`下面测试通过.

**Comment by guaxiao** [comment]
那我稍后 merge 到 master 了，谢谢两位。

**Comment by happlebao** [comment]
@plinx pull 我最新的`visualstudio`,你再试下?

**Comment by plinx** [comment]
@happlebao ，好的，我在上班，回去才能试。

**Comment by happlebao** [comment]
不过输出位置有点怪,下面空了好大一块:
![screentshot](http://i.imgur.com/4vNX1H5.png)

**Comment by guaxiao** [comment]
这是因为这个模型的原点在脚。
你可以用 w s 移动模型，方向键旋转模型

**Comment by happlebao** [comment]
这样,十分感谢.
